--To create the warehouse

CREATE WAREHOUSE IF NOT EXISTS HOSPITAL_MANAGE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

--create the database

CREATE DATABASE IF NOT EXISTS HOSPITAL_MANAGE_DB;
USE DATABASE HOSPITAL_MANAGE_DB;

--create the Schema 

CREATE SCHEMA HOSPITAL_SCHEMA;
USE SCHEMA HOSPITAL_SCHEMA;

CREATE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY='"';

--create the stage 

CREATE STAGE HOSPITAL_STAGE
FILE_FORMAT = CSV_FORMAT;

--create the DIM_PATIENT 

CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_ID NUMBER NOT NULL,
    FULL_NAME STRING,
    DOB DATE,
    GENDER STRING,
    PHONE STRING,
    EMAIL STRING,
    CITY STRING,
    STATE STRING,
    REGISTRATION_DATE DATE
);

--create the DIM_DOCTORS

CREATE OR REPLACE TABLE DIM_DOCTORS AS
SELECT DISTINCT
  DOCTOR_ID,
  DOCTOR_NAME,
  DEPARTMENT
FROM FACT_APPOINTMENTS;

--create the appointment 

CREATE OR REPLACE TABLE FACT_APPOINTMENT (
    APPT_ID NUMBER,
    APPT_DATE DATE NOT NULL,
    PATIENT_ID NUMBER NOT NULL,
    DOCTOR_ID NUMBER,
    DEPARTMENT STRING,
    SLOT STRING,
    STATUS STRING CHECK (
        STATUS IN ('Scheduled','Completed','No-Show','Cancelled')
    )
);

--create the billing 

CREATE OR REPLACE TABLE FACT_BILLING (
    BILL_ID NUMBER,
    BILL_DATE DATE NOT NULL,
    PATIENT_ID NUMBER NOT NULL,
    SERVICE_CODE STRING,
    SERVICE_DESC STRING,
    DEPARTMENT STRING,
    GROSS_AMOUNT NUMBER(10,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    TAX_AMOUNT NUMBER(10,2),
    NET_AMOUNT NUMBER(10,2) CHECK (NET_AMOUNT >= 0),
    PAYMENT_MODE STRING,
    INSURER_NAME STRING
);

--exception record

CREATE OR REPLACE TABLE EXCEPTION_RECORDS (
    ERROR_TYPE STRING,
    RECORD_DETAILS STRING,
    LOAD_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

--copy from stage 

COPY INTO DIM_PATIENT
FROM @HOSPITAL_STAGE
FILES = ('patients_master_clean.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
FORCE = TRUE;

COPY INTO FACT_APPOINTMENTS
FROM @HOSPITAL_STAGE
FILES = ('appointments_clean.csv')
FILE_FORMAT = (FORMAT_NAME ='CSV_FORMAT')
FORCE = TRUE;

COPY INTO FACT_BILLING
FROM @HOSPITAL_STAGE
FILES = ('billing_clean.csv')
FILE_FORMAT = (FORMAT_NAME ='CSV_FORMAT')
FORCE = TRUE;

select * from DIM_DOCTORS;

--create view 

CREATE or replace VIEW VW_DEPT_APPT_SUMMARY AS
SELECT
DEPARTMENT,
COUNT(*) TOTAL_APPOINTMENTS
FROM FACT_APPOINTMENTS
GROUP BY DEPARTMENT;

select * from VW_DEPT_APPT_SUMMARY;

-- create a view for revenue 

CREATE VIEW VW_REVENUE_BY_DEPT AS
SELECT
DEPARTMENT,
SUM(NET_AMOUNT) TOTAL_REVENUE
FROM FACT_BILLING
GROUP BY DEPARTMENT;

select * from VW_REVENUE_BY_DEPT;

-- create a view for daily appointment 

CREATE OR REPLACE VIEW VW_DAILY_OPD_TREND AS
SELECT
APPT_DATE,
COUNT(*) TOTAL_VISITS
FROM FACT_APPOINTMENTS
GROUP BY APPT_DATE;

select * from VW_DAILY_OPD_TREND;

--stream
CREATE OR REPLACE STREAM APPT_STREAM
ON TABLE FACT_APPOINTMENTS;
INSERT INTO FACT_APPOINTMENTS (
    APPT_ID,APPT_DATE,PATIENT_ID,DOCTOR_ID,DEPARTMENT,SLOT,STATUS
)VALUES (
    1001, '2026-05-29',1,101,'Cardiology','10:00 AM','Completed'
);
SELECT * FROM APPT_STREAM;

--task
CREATE OR REPLACE TASK DAILY_TASK
WAREHOUSE = HOSPITAL_MANAGE_WH
SCHEDULE = '1 MINUTES'
AS
SELECT CURRENT_TIMESTAMP;

SHOW TASKS LIKE 'DAILY_TASK';

--secure view 
USE SCHEMA HOSPITAL_SCHEMA;
CREATE ROLE IF NOT EXISTS DOCTOR_ROLE;
CREATE ROLE IF NOT EXISTS BILLING_ROLE;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS AUDITOR_ROLE;
CREATE ROLE IF NOT EXISTS ADMIN_ROLE;

--doctor view
CREATE OR REPLACE SECURE VIEW SV_DOCTOR_VIEW AS
SELECT
    P.PATIENT_ID,P.FULL_NAME,P.GENDER,A.APPT_ID,A.APPT_DATE,A.DEPARTMENT,A.STATUS
FROM DIM_PATIENT P
JOIN FACT_APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID;

GRANT SELECT ON VIEW SV_DOCTOR_VIEW
TO ROLE DOCTOR_ROLE;

--billing view
CREATE OR REPLACE SECURE VIEW SV_BILLING_VIEW AS
SELECT
    BILL_ID,BILL_DATE,PATIENT_ID,DEPARTMENT,NET_AMOUNT,PAYMENT_MODE,INSURER_NAME
FROM FACT_BILLING;

GRANT SELECT ON VIEW SV_BILLING_VIEW
TO ROLE BILLING_ROLE;

--analystic view
CREATE OR REPLACE SECURE VIEW SV_ANALYST_VIEW AS
SELECT
    DEPARTMENT,COUNT(*) TOTAL_APPOINTMENTS
FROM FACT_APPOINTMENT
GROUP BY DEPARTMENT;

GRANT SELECT ON VIEW SV_ANALYST_VIEW
TO ROLE ANALYST_ROLE;

CREATE TABLE IF NOT EXISTS APPOINTMENT_AUDIT
(
 APPT_ID NUMBER, ACTION_TYPE STRING, ACTION_TIME TIMESTAMP
);

--auditor role
CREATE OR REPLACE SECURE VIEW SV_AUDITOR_VIEW AS
SELECT
    APPT_ID, ACTION_TYPE, ACTION_TIME
FROM APPOINTMENT_AUDIT;

GRANT SELECT ON VIEW SV_AUDITOR_VIEW
TO ROLE AUDITOR_ROLE;

--admin role
CREATE ROLE IF NOT EXISTS ADMIN_ROLE;
GRANT ALL PRIVILEGES
ON DATABASE HOSPITAL_MANAGE_DB
TO ROLE ADMIN_ROLE;

ALTER COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU SUSPEND;
ALTER COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU RESUME;
